[package]
name = "srcpit-uri"
version = "0.1.0"
authors = ["Bernd Vogt <bernd.vogt@sourcepit.org>"]

[dependencies]
srcpit-token-buf = { path = "../srcpit-token-buf" }
failure = "0.1.3"
common_failures = "0.1.1"